[package]
name = "navi-json"
version = "0.1.0"
edition = "2021"
author = "Giulio Toldo"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.7", features = ["derive"] }
json = "0.12.4"
